import type { ScoringStatDefinition } from "@/lib/leagues/scoring/stats/types";

export const DEFENSE_STATS: ScoringStatDefinition[] = [
  {
    id: "assisted-tackles",
    label: "Assisted Tackles",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "solo-tackles",
    label: "Solo Tackles",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "tackles-for-loss",
    label: "Tackles For Loss",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "interceptions",
    label: "Interceptions",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "sacks",
    label: "Sacks",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "sack-yards",
    label: "Sack Yards",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fumbles-forced",
    label: "Fumbles Forced",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fumbles-recovered",
    label: "Fumbles Recovered",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "opposing-fumble-recoveries",
    label: "Opposing Fumble Recoveries",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "safeties",
    label: "Safeties",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "defensive-tds-quantity",
    label: "Defensive TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "defensive-tds-distance",
    label: "Defensive TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "blocked-fg-return-tds-quantity",
    label: "Blocked FG Return TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "missed-fg-return-tds-quantity",
    label: "Missed FG Return TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fumble-return-tds-quantity",
    label: "Fumble Return TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "int-return-tds-quantity",
    label: "INT Return TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blocked-punt-return-tds-quantity",
    label: "Blocked Punt Return TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blocked-fg-return-tds-distance",
    label: "Blocked FG Return TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "missed-fg-return-tds-distance",
    label: "Missed FG Return TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "fumble-return-tds-distance",
    label: "Fumble Return TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "int-return-tds-distance",
    label: "INT Return TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "blocked-punt-return-tds-distance",
    label: "Blocked Punt Return TDs (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "xps-blocked",
    label: "XPs Blocked",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fgs-blocked",
    label: "FGs Blocked",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "punts-blocked",
    label: "Punts Blocked",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blocked-kicks",
    label: "Blocked Kicks",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blocked-kick-tds-quantity",
    label: "Blocked Kick TDs (Quantity)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blocked-kick-td-yards-distance",
    label: "Blocked Kick TD Yards (Distance)",
    category: "defense",
    templateSet: "distance",
  },
  {
    id: "passes-defended",
    label: "Passes Defended",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "times-targeted",
    label: "Times Targeted",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "completions-against",
    label: "Completions Against",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "points-allowed",
    label: "Points Allowed",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "offensive-points-allowed",
    label: "Offensive Points Allowed (FG, Pass TD, Rush TD)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "special-teams-points-allowed",
    label: "Special Teams Points Allowed (Return TD, XP, 2-Pt Conv)",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "offensive-special-teams-points-allowed",
    label: "Offensive + Special Teams Points Allowed",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "net-yards-allowed",
    label: "Net Yards Allowed",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "net-passing-yards-allowed",
    label: "Net Passing Yards Allowed",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "net-rushing-yards-allowed",
    label: "Net Rushing Yards Allowed",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "qb-hits",
    label: "QB Hits",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "qb-hurries",
    label: "QB Hurries",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "blitzes",
    label: "Blitzes",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "conversion-returns",
    label: "Conversion Returns",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fourth-down-stops",
    label: "Fourth-Down Stops",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "three-and-outs",
    label: "Three and Outs",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "interception-return-yards",
    label: "Interception Return Yards",
    category: "defense",
    templateSet: "quantity",
  },
  {
    id: "fumble-return-yards",
    label: "Fumble Return Yards",
    category: "defense",
    templateSet: "quantity",
  },
];
