import type { TeamStatsChartsData } from "@/lib/queries/team-stats-charts";

/** Design preview for Team Stats charts. Enable with `?mock=1` on team Stats. */
export function getTeamStatsChartsMock(): TeamStatsChartsData {
  return {
    weeklyPoints: [
      { week: 1, label: "W1", team: 118.4, high: 142.2, low: 78.1, median: 105.6 },
      { week: 2, label: "W2", team: 96.2, high: 138.8, low: 71.4, median: 102.1 },
      { week: 3, label: "W3", team: 131.7, high: 151.0, low: 84.3, median: 109.8 },
      { week: 4, label: "W4", team: 104.5, high: 129.6, low: 88.0, median: 107.2 },
      { week: 5, label: "W5", team: 88.9, high: 144.1, low: 69.5, median: 101.4 },
      { week: 6, label: "W6", team: 122.3, high: 136.4, low: 82.7, median: 110.0 },
      { week: 7, label: "W7", team: 115.8, high: 140.2, low: 76.9, median: 108.5 },
      { week: 8, label: "W8", team: 109.1, high: 133.7, low: 90.2, median: 106.3 },
    ],
    positionMix: [
      {
        positionId: "QB",
        label: "QB",
        fullLabel: "Quarterback",
        points: 186.4,
        teamShare: 18.2,
        leagueShare: 16.5,
      },
      {
        positionId: "RB",
        label: "RB",
        fullLabel: "Running back",
        points: 241.8,
        teamShare: 23.6,
        leagueShare: 24.1,
      },
      {
        positionId: "WR",
        label: "WR",
        fullLabel: "Wide receiver",
        points: 312.5,
        teamShare: 30.5,
        leagueShare: 26.8,
      },
      {
        positionId: "TE",
        label: "TE",
        fullLabel: "Tight end",
        points: 64.2,
        teamShare: 6.3,
        leagueShare: 9.4,
      },
      {
        positionId: "FLEX",
        label: "FLEX",
        fullLabel: "Flex",
        points: 98.7,
        teamShare: 9.6,
        leagueShare: 10.2,
      },
      {
        positionId: "K",
        label: "K",
        fullLabel: "Kicker",
        points: 72.1,
        teamShare: 7.0,
        leagueShare: 6.8,
      },
      {
        positionId: "DEF",
        label: "DEF",
        fullLabel: "Defense",
        points: 48.9,
        teamShare: 4.8,
        leagueShare: 6.2,
      },
    ],
    // Shape inspired by classic FF schedule luck (all-play expected vs H2H).
    weeklyLuck: [
      {
        week: 1,
        label: "W1",
        luck: 31,
        rank: 5,
        teamCount: 14,
        result: "W",
        points: 118.4,
        opponentPoints: 102.1,
        expectedWinPct: 0.692,
      },
      {
        week: 2,
        label: "W2",
        luck: 8,
        rank: 2,
        teamCount: 14,
        result: "W",
        points: 96.2,
        opponentPoints: 88.4,
        expectedWinPct: 0.923,
      },
      {
        week: 3,
        label: "W3",
        luck: -62,
        rank: 6,
        teamCount: 14,
        result: "L",
        points: 131.7,
        opponentPoints: 151.0,
        expectedWinPct: 0.615,
      },
      {
        week: 4,
        label: "W4",
        luck: 23,
        rank: 4,
        teamCount: 14,
        result: "W",
        points: 104.5,
        opponentPoints: 98.2,
        expectedWinPct: 0.769,
      },
      {
        week: 5,
        label: "W5",
        luck: 0,
        rank: 1,
        teamCount: 14,
        result: "W",
        points: 144.1,
        opponentPoints: 101.4,
        expectedWinPct: 1,
      },
      {
        week: 6,
        label: "W6",
        luck: 23,
        rank: 4,
        teamCount: 14,
        result: "W",
        points: 122.3,
        opponentPoints: 110.0,
        expectedWinPct: 0.769,
      },
      {
        week: 7,
        label: "W7",
        luck: 0,
        rank: 1,
        teamCount: 14,
        result: "W",
        points: 140.2,
        opponentPoints: 108.5,
        expectedWinPct: 1,
      },
      {
        week: 8,
        label: "W8",
        luck: 85,
        rank: 12,
        teamCount: 14,
        result: "W",
        points: 92.1,
        opponentPoints: 90.2,
        expectedWinPct: 0.154,
      },
    ],
    benchWaste: [
      {
        week: 1,
        label: "W1",
        leftOnBench: 12.4,
        pointsFor: 118.4,
        optimumPointsFor: 130.8,
        opponentPoints: 102.1,
        result: "W",
        wouldHaveFlipped: false,
      },
      {
        week: 2,
        label: "W2",
        leftOnBench: 4.1,
        pointsFor: 96.2,
        optimumPointsFor: 100.3,
        opponentPoints: 88.4,
        result: "W",
        wouldHaveFlipped: false,
      },
      {
        week: 3,
        label: "W3",
        leftOnBench: 22.8,
        pointsFor: 131.7,
        optimumPointsFor: 154.5,
        opponentPoints: 151.0,
        result: "L",
        wouldHaveFlipped: true,
      },
      {
        week: 4,
        label: "W4",
        leftOnBench: 0,
        pointsFor: 104.5,
        optimumPointsFor: 104.5,
        opponentPoints: 98.2,
        result: "W",
        wouldHaveFlipped: false,
      },
      {
        week: 5,
        label: "W5",
        leftOnBench: 18.6,
        pointsFor: 88.9,
        optimumPointsFor: 107.5,
        opponentPoints: 101.4,
        result: "L",
        wouldHaveFlipped: true,
      },
      {
        week: 6,
        label: "W6",
        leftOnBench: 7.2,
        pointsFor: 122.3,
        optimumPointsFor: 129.5,
        opponentPoints: 110.0,
        result: "W",
        wouldHaveFlipped: false,
      },
      {
        week: 7,
        label: "W7",
        leftOnBench: 3.4,
        pointsFor: 115.8,
        optimumPointsFor: 119.2,
        opponentPoints: 108.5,
        result: "W",
        wouldHaveFlipped: false,
      },
      {
        week: 8,
        label: "W8",
        leftOnBench: 15.1,
        pointsFor: 109.1,
        optimumPointsFor: 124.2,
        opponentPoints: 90.2,
        result: "W",
        wouldHaveFlipped: false,
      },
    ],
    gamesFlippedByBench: 2,
    kpis: {
      avgWinMargin: { average: 45.8, sampleSize: 6 },
      avgLossMargin: { average: -18.3, sampleSize: 2 },
      avgWeeklyScore: {
        average: 110.9,
        sampleSize: 8,
        consistencyPlusMinus: 14.2,
        consistency: "good",
      },
    },
  };
}
